# Deployment = il maintient en permanence un nombre voulu de Pods (repliques).
# Si un Pod meurt, Kubernetes en recree un automatiquement (auto-reparation).
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web
  labels:
    app: demo-web
spec:
  replicas: 3                       # 3 Pods identiques
  selector:
    matchLabels:
      app: demo-web                 # ce Deployment gere les Pods portant ce label
  template:                         # ---- modele de Pod ----
    metadata:
      labels:
        app: demo-web               # label appose sur chaque Pod (utilise par le Service)
    spec:
      containers:
        - name: web
          image: demo-k8s:1.0
          imagePullPolicy: IfNotPresent   # utilise l'image locale (pas de pull sur un registre)
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: demo-config    # injecte toutes les cles du ConfigMap comme variables d'env
          readinessProbe:            # le Pod recoit du trafic seulement quand il repond
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:             # si le Pod est bloque, K8s le redemarre
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
